name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - run: dotnet publish -c Release
      working-directory: ./dotnet
    - name: Create issue using REST API
      run: |
        curl \
        --url https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' | tee artefacts
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: binary
        # Directory containing files to upload
        path: ./dotnet/bin/Release/netcoreapp3.1/publish
