name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - run: dotnet publish -c Release
      working-directory: ./dotnet
    - run: |
      curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" "https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts" | jq ".artifacts | .[] | .id" | tee artefacts
      cat artefacts | xargs -n1 -i curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -X DELETE "https://api.github.com/repos/${{github.repository}}/actions/artifacts/{}"
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: binary
        # Directory containing files to upload
        path: ./dotnet/bin/Release/netcoreapp3.1/publish
