name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - run: dotnet test
      working-directory: ./dotnet
    - name: Remove old artifacts
      run: |
        curl \
        --url https://api.github.com/repos/${{github.repository}}/actions/artifacts \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' | jq ".artifacts | .[] | .id" | tee artefacts
        tail -n +3 artefacts | xargs -n1 -i curl -X DELETE \
        --url https://api.github.com/repos/${{github.repository}}/actions/artifacts/{} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json'
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: binary
        # Directory containing files to upload
        path: ./texts
